FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=haslo
ENV MYSQL_DATABASE=basketball-stats
ENV MYSQL_USER=basketball-fan
ENV MYSQL_PASSWORD=haslo
ENV MYSQL_HOST=myhost

#ADD tables_def.sql /docker-entrypoint-initdb.d
#ADD insert.sql /docker-entrypoint-initdb.d

EXPOSE 3306